blank_issues_enabled: false
contact_links:
  - name: ğŸ‘€ Githubè®ºå› | GitHub Discussions
    url: https://github.com/OrdinaryRoad-Project/ordinaryroad-live-chat-client/discussions
    about: å¦‚æœæ‚¨çš„é—®é¢˜ä¸æ˜¯åŠŸèƒ½æˆ–è€…é”™è¯¯ï¼Œè¯·è½¬åˆ°è®¨è®ºé¢æ¿å¹¶åœ¨æäº¤ä¹‹å‰æ£€ç´¢æ‚¨çš„é—®é¢˜æ˜¯å¦å·²ç»å­˜åœ¨ã€‚
